### ISSUE TITLE
Missing installing the requirements on ulauncher extension description

### ISSUE THREAD

**Issue by hillaryychan** [hillaryychan/ulauncher-fzf#14]
After reading and installing the requirements on the GitHub page.... it works! :smiley: :+1: 

Please put a little reminder on the extension description page that one should install those tools first. (I'm a coder, but I'm intentionally doing this from a users' perspective)

_Originally posted by @oktayacikalin in https://github.com/hillaryychan/ulauncher-fzf/issues/9#issuecomment-1015411066_

---

Make it clear that fzf and fd should be installed for extension to be used on https://ext.ulauncher.io/-/github-hillaryychan-ulauncher-fzf

**Comment by hillaryychan** [comment]
Update description to explicitly state fzf and fd need to be installed.
![image](https://user-images.githubusercontent.com/44228565/150076635-ea7f9ba2-7ee6-45b5-8138-fd37b419cce3.png)

**Comment by BenoitDuffez** [comment]
To save some a minute of Google search:

* https://github.com/junegunn/fzf
* https://github.com/sharkdp/fd

**Comment by vipseixas** [comment]
> To save some a minute of Google search:
> 
> * https://github.com/junegunn/fzf
> * https://github.com/sharkdp/fd

Just to add, it is far from being clear which fd must be installed (at least at Ubuntu 22.04). There is no fd package in Ubuntu and the shell gives this (wrong) hint:

```
$ fd
Command 'fd' not found, but can be installed with:
sudo apt install fdclone
```
