### ISSUE TITLE
Custom number of search results

### ISSUE THREAD

**Issue by hillaryychan** [hillaryychan/ulauncher-fzf#15]
Works like a charm now. Thank you for fixing this so fast and also for this beautiful extension! This is exactly what I was looking for. :)

Do you know by any chance, if/how I can make ulauncher output more than 15 results?

_Originally posted by @hemanti0503 in https://github.com/hillaryychan/ulauncher-fzf/issues/9#issuecomment-1015415204_

---

Allow users to define custom number of search results for the extension

**Comment by hemanti0503** [comment]
Works! Thank you! :)
