### ISSUE TITLE
searching beyond the home directory?

### ISSUE THREAD

**Issue by 88-percent** [hillaryychan/ulauncher-fzf#25]
The uLauncher-fzf extension is great! I agree with many others [here](https://github.com/Ulauncher/Ulauncher/issues/963) that this functionality should be rolled into uLauncher by default.

Not sure if this is a feature request or simply a setup question (setting a config file or creating some strategic symlinks perhaps?), but is there any way I can expand the search beyond the home directory?

For regulatory compliance reasons I'm required to keep a subset of my files on a separate LUKS partition. I'd love to be able to access the files using uLauncher-fzf if at all possible.

Thanks!

**Comment by hillaryychan** [comment]
Hi there!

Just to help me understand your use case a bit more, is the LUKS partition accessible from another path on `/` or can you create a symlink to it?

Not really familiar with partitions so any other details or links to resources about LUKS would be great too.

**Comment by 88-percent** [comment]
Your questions got me to think about this in a way that helped me answer this. Thanks so much.

I probably needlessly complicated the question by bringing the LUKS encrypted partition into things. As far as the system is concerned, my encrypted partition is transparent, as it acts like a standard partition. I currently mount it at a subdirectory of /mnt and can symlink to it without issue. 

I'd previously tried to create a symlink to directories located on the partition but the uLauncher-fzf extension unfortunately wasn't following the link. I could see and open the symlink itself, but was unable to follow it through.

What your question made me think about was if I could simply change my mount point from /mnt/partition to a subdirectory of my home directory. I was able to test this using a flash drive and was successful in getting the contents to display using the extension. I'll try to remap my main partition, but I'll need some time to back the world away as it will break a number of links I'll need to remap. Worth the effort to get your great extension up and running though!

I'm going to close this issue, but if you can think of a more elegant solution I'd love to hear about it. 

Thanks again.
