### ISSUE TITLE
please show example on how to ignore a file and path

### ISSUE THREAD

**Issue by chaibronz** [hillaryychan/ulauncher-fzf#28]
I really enjoy using this extension (great work!), but would like to ignore searching some directories and not sure what ".gitignore format" means when you say to "Specify path to ignore-file in '.gitignore' format",  Could you provide a few examples of what the format looks like if you want to ignore:

1. one file
2. more than one file
3. one directory
4. more than one directory

**Comment by hillaryychan** [comment]
Hi there,

`.gitignore` format is simply like using a `.gitignore` file. You just list the files and directories you want to get ignored (with one file/directory on each line). It's as simple as that.

As for using it, you create a file to contain the list of files/directories you want to ignore. You can call it whatever you want, I've called mine `.ulauncherignore`. Then in the settings of the extension, you specify the path to the file.

I believe the idea of a `.gitignore` file format should be self-explanatory, especially for something like GitHub, but I will update the feature description for this to be a bit more explicit.
