### ISSUE TITLE
Allow to follow symbolic links

### ISSUE THREAD

**Issue by rcfgnu** [hillaryychan/ulauncher-fzf#30]
Hi, should be nice to have an option(similar to hidden files) to pass --follow to fd and follow symbolic links.
Thanks

**Comment by hillaryychan** [comment]
Sounds like something good to add. Not sure how following symlinks slipped my mind since I do use them quite a bit - but never for searching for them.
I'll raise a PR for that soon

**Comment by hillaryychan** [comment]
I've tested the option locally and it seems to work fine for me. Let me know if there are any issues.
