### ISSUE TITLE
Feature request: copy path on ctrl+enter

### ISSUE THREAD

**Issue by zorzysty** [hillaryychan/ulauncher-fzf#33]
Opening a file or directory are definitely the most important features, but I would find it very useful to have a way to copy the highlighted file path. Sometimes you just need to find some file and paste its path somewhere.

**Comment by hillaryychan** [comment]
Hi there, copying a file path is a valid use case that I also encounter sometimes. 

It doesn't look like there are alternative keybindings that I can assign to a selected result item aside from `Enter` and `Alt+Enter`. I believe opening a file is the core feature for this extension, so I think the best approach to this would be to allow users to select their preferred behaviour for the `Alt+Enter` keybinding. When I have time, I'll raise a PR that lets you set copying the file path when you `Alt+Enter`. To avoid breaking existing behaviour, this will default `Alt+Enter` to open the directory.

**Comment by hillaryychan** [comment]
I've tested the changes locally, and it works fine for me on Python 3.10. 

Let me know if there are any issues :slightly_smiling_face:
