### ISSUE TITLE
On by default / no keyword

### ISSUE THREAD

**Issue by Muttsuri** [hillaryychan/ulauncher-fzf#40]
Is it possible for fzf to be launched always and be merged with other searches, or is this not possible with this launcher ?
I don't know if this is a silly question, sorry if it.
I ask this since I've used other launchers (mainly on Windows and currently flow-launcher) and even krunner seemed to have the ability to do both. I wonder if this is possible here, but I am not sure if it is on the configuration of this plugin or something needs to be changed upstream.
Thank you for your attention.

**Comment by hillaryychan** [comment]
Hi @Muttsuri the architecture of ulauncher's extension framework relies on a created extension handling custom keywords, which is defaulted to `fzf` for this extension. Unfortunately, there isn't much I can help with here.

From http://docs.ulauncher.io/en/stable/extensions/intro.html

> Extension API v2 (current) enables extension developers to write custom handlers for keywords.
> ...
> They cannot modify behaviour or look of Ulauncher app. They can only be used to handle an input that starts with a keyword, which extension developers define in a manifest file.
