### ISSUE TITLE
FZF is not found even if it is installed

### ISSUE THREAD

**Issue by eriksdev1** [hillaryychan/ulauncher-fzf#41]
Good day, I installed the extension for ulauncher from the ulauncher site and found this github site, I'm creating an issue as I have installed fzf from its own github and is working but ulauncher's extension is not detecting it, any help is much appreciated

![image](https://github.com/hillaryychan/ulauncher-fzf/assets/45124393/7970feed-92b1-4b08-a14e-da4576d7aecb)

im on debian 12 stable, xfce, gnome dark prof theme

Thank you

**Comment by friday** [comment]
You haven't installed fzf to a location inside your $PATH. If you had installed it, then `which fzf` would print the location (/usr/bin/fzf), you could call it by just typing `fzf` from any location, and this extension would not show this warning.

What you have done is probably to build and run it from the source, or maybe installed it to a location outside of PATH.

Since you're on Debian, run `sudo apt install fzf`.

**Comment by eriksdev1** [comment]
@friday  thank you so much, knowing the default install path of (/usr/bin/fzf), and `which fzf` helped me, thank you so much !!

**Comment by DerTobi75** [comment]
@friday & @hillaryychan 
I had to reinstall fzf, because I needed a newrer Version of fzf for another tool. So I installed fzf from GIT in /home/tobias/.fzf/bin/fzf that path is also added to my $PATH Variable. 

But I still get the Error Message about the Missing Dependency.

**Comment by friday** [comment]
So if you run which fzf it shows that? And if you run `PATH=$(getconf PATH) which fzf` it does not? Sounds like https://github.com/Ulauncher/Ulauncher/discussions/1351

**Comment by DerTobi75** [comment]
Ok thanks, so I would extend that file like:

[Service]
Enviroment="FZF=/home/tobias/.fzf/bin/fzf"

**Comment by friday** [comment]
No. That would set FZF as an environment variable, you'd have to do something like PATH="/home/tobias/.fzf/bin:$PATH", but that's a very backwards approach.

Your want your system dependencies using other system dependencies, not binaries in your home dir. So install it proper from the system package and keep your custom build, as that should override that one for you (assuming you appended to your path correctly), but not Ulauncher.

**Comment by friday** [comment]
Basically `sudo apt install fzf` or whatever your package manager command is, then it should work. If `which fzf` still outputs your local version, then it will work.

**Comment by DerTobi75** [comment]
Ubuntu as an old version of FZF in their Package Manager, which is too old for another tool I am using :-(

**Comment by DerTobi75** [comment]
You can close that issue. Found a workaround for me, to get ulauncher work with my FZF Version.

Thanks for your help.

**Comment by souhaiebtar** [comment]
you can just use symlink, it did work for me,

`sudo ln -s /home/MY_USERNAME/.fzf/bin/fzf /usr/bin/fzf`

you can change ` /home/MY_USERNAME/.fzf/bin/fzf`  with the path of `fzf` in your system
